name: AUCE
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUCE_SETTINGS: ${{ secrets.AUCE_SETTINGS }}
      
permissions: write-all

jobs:
  Run:
#    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          cache: pip
      
      - name: Clone repo
        run: |
          git clone --depth 1 https://github.com/samin-irtiza/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE
          cd Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/
          rm -rf .github .git
          mv * ../
          rm -rf Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE

      - name: Install requirements and Udemy
        run: |
          pip install -r requirements.txt
          pip install udemy-enroller

      - name: Download settings.yaml
        run: |
          wget -O settings.yaml ${{ env.AUCE_SETTINGS }} > /dev/null 2>&1
          sudo mkdir /home/runner/.udemy_enroller
          sudo mv -f settings.yaml /home/runner/.udemy_enroller/settings.yaml

#      - name: Setup Chrome
#        uses: browser-actions/setup-chrome@master

      - name: Setup Chrome
        uses: nanasess/setup-chromedriver@v2

#      - name: Assign permissions
#        run: |
#          chmod +x /home/runner/.udemy_enroller/*

      - name: Enroll time
        timeout-minutes: 30
        continue-on-error: true
        run: udemy_enroller

  Delete_old_workflows:
    runs-on: ubuntu-latest
    steps:    
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          older-than-seconds: 604800
          repository: ${{ github.repository }}
