name: Udemy Enroller
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  Run:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Download files
        run: |
          curl -O ${{ secrets.CONFIG }}
          curl -O https://github.com/techtanic/Discounted-Udemy-Course-Enroller/releases/latest/download/DUCE-CLI-windows.exe
      - name: Run  
        run: |
          DUCE-CLI-windows.exe
          
