name: Udemy Enroller
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
permissions: write-all

jobs:
  Run:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Download files
        run: |
          cd
          Start-BitsTransfer -Source ${{ secrets.CONFIG }} -Destination ./duce-cli-settings.json
          Start-BitsTransfer -Source https://github.com/techtanic/Discounted-Udemy-Course-Enroller/releases/latest/download/DUCE-CLI-windows.exe -Destination ./DUCE-CLI-windows.exe
          dir
      - name: Run  
        run: |
          cd
          DUCE-CLI-windows.exe

  Delete_old_workflows:
    runs-on: ubuntu-latest
    steps:    
      - name: Delete old workflow runs
        # You may pin to the exact commit or the version.
        # uses: MajorScruffy/delete-old-workflow-runs@78b5af714fefaefdf74862181c467b061782719e
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          older-than-seconds: 604800
