name: Udemy Enroller
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * */4'

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
permissions: write-all

jobs:
  Run:
#    timeout-minutes: 5
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@main
        with: |
          cache: pip
      
      - name: Download requirements and install requirements
        run: |
          Start-BitsTransfer -Source https://raw.githubusercontent.com/techtanic/Discounted-Udemy-Course-Enroller/master/requirements.txt -Destination .\requirements.txt
          pip install requirements.txt

      - name: Download files
        run: |
          Start-BitsTransfer -Source ${{ secrets.CONFIG }} -Destination .\duce-cli-settings.json
          Start-BitsTransfer -Source https://github.com/techtanic/Discounted-Udemy-Course-Enroller/releases/latest/download/DUCE-CLI-windows.exe -Destination .\DUCE-CLI-windows.exe

      - name: Enroll time
        shell: cmd
        timeout-minutes: 30
        continue-on-error: true
        run: |
          DUCE-CLI-windows.exe

  Delete_old_workflows:
    runs-on: ubuntu-latest
    steps:    
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          older-than-seconds: 604800
          repository: ${{ github.repository }}
